"""empty message

Revision ID: af6579c56b5c
Revises: 04b769368ff1
Create Date: 2018-12-08 11:16:38.043406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6579c56b5c'
down_revision = '04b769368ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('page_views', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'slug')
    op.drop_column('projects', 'page_views')
    # ### end Alembic commands ###
